runtime: nodejs16

handlers:
  # Serve the React app on all URLs
  - url: /.*
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html

  # Serve static files for the React app
  - url: /(.*)
    static_files: frontend/dist/\1
    upload: frontend/dist/(.*)

  # Serve the backend on all URLs that start with /api
  - url: /api/.*
    script: backend/server.js

env_variables:
  DB_URI: "mongodb+srv://grantpan:gpan7879@cluster0.mgtgo2g.mongodb.net/3350_project?retryWrites=true&w=majority"
  PORT: "4000"
  ACCESS_TOKEN_SECRET: "4b1e67f6e5c8973e841ce716f89c54dec61352d07b7d552a2bd668ec4fe34dc7744223f6575d62ec870ea599c8f61548d9f189c0930c37dbde235a00ad7404ec"
