runtime: nodejs16
env_variables:
  DB_URI: "mongodb+srv://grantpan:gpan7879@cluster0.mgtgo2g.mongodb.net/3350_project?retryWrites=true&w=majority"
  PORT: "4000"
  ACCESS_TOKEN_SECRET: "4b1e67f6e5c8973e841ce716f89c54dec61352d07b7d552a2bd668ec4fe34dc7744223f6575d62ec870ea599c8f61548d9f189c0930c37dbde235a00ad7404ec"

handlers:
  # Serve the backend on all URLs that start with /api
  - url: /api/.*
    script: server.js
